server:
  port: 9001
---
spring:
    profiles: local
mason:
  value: local-changed
---
spring:
    profiles: develop
mason:
  value: develop
---
spring:
    profiles: production
mason:
  value: production
